### ISSUE TITLE
error: package android.support.test.rule does not exist

### ISSUE THREAD

**Issue by Phlip** [NileshJarad/TDD_Demo#3]
I can run the unit tests, but I can't run ActivityTests. I always get:

`error: package android.support.test.rule does not exist`

The reply here, https://github.com/firebase/friendlychat-android/issues/65 , says to add `androidTestImplementation 'com.android.support.test:rules:1.0.2'` to app/build.gradle, but that didn't work.

The versions are Android 8.0.0 API 26.

Other than that thanks for the awesome tutorial - everyone should TDD everywhere, but of course many platforms, such as Android, make it unnecessarily hard

**Comment by Phlip** [comment]
One Rapunzel Van Winkle figured it out. We need to upgrade from com.android to androidx:

https://stackoverflow.com/questions/56532069/android-espresso-activitytest-gives-package-android-support-test-rule-does-not

**Comment by NileshJarad** [comment]
Thanks @Phlip. As issue resolved I am closing it.
